### ISSUE TITLE
Review code and suggestions from teammates

### ISSUE THREAD

**Issue by marcelomaidden** [jcy2704/Forms#3]
Review code used on Morning Session Peer to Peer Code review from Microverse Students Team 155

**Comment by carloso0114** [comment]
to me it's perfect , well done.

**Comment by StarSheriff2** [comment]
Code looks clean and organized. ReadMe.md file needs to be more descriptive though

**Comment by marcelomaidden** [comment]
The project was really well done, congratulations.
